version: '3.7'

services:
  db:
    image: postgres
    restart: always
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dbtest
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password

  app:
    image: staff-project-test
    build:
      context: .
      dockerfile: DockerfileTest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dbtest
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password