version: '3.8'            # Version 3.8 is quite new and should work

services:
  docker-dind:
    image: docker:dind
    container_name: docker_dind
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client

    environment:
      DOCKER_TLS_CERTDIR: /certs
    privileged: true
    networks:
      jenkins-network:
#        aliases:
#          - dockerdindalias

  jenkins-docker:
    image: jenkins-docker
    build:
      context: .
      dockerfile: DockerfileJenkins
    container_name: jenkins_docker
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    ports:
      - "7080:8080"
    depends_on:
      - docker-dind
    environment:
      DOCKER_HOST: tcp://docker_dind:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    networks:
      jenkins-network:

volumes:
  jenkins-data:
  jenkins-docker-certs:

networks:
  jenkins-network: